CC=mpicc
BUILD_DIR=out
PROGRAM_NAME=asfalto
INCLUDE =include
FLAGS   = -O0 -g -fopenmp
LIBS    = -lm
SOURCE  = $(wildcard src/*.c)
BUILD   = build
INCLUDE = include

# Defaults
DEFAULT_POPULATION_SIZE=1000
DEFAULT_GENES_PER_INDIVIDUAL=5
DEFAULT_LOWER_GENE_LIMIT=0
DEFAULT_UPPER_GENE_LIMIT=100
DEFAULT_MUTATION_CHANCE_PERCENT=30
DEFAULT_CROSSOVER_CHANCE_PERCENT=50
DEFAULT_MAX_GENERATIONS=10

MAX_POPULATION=1000
MAX_GEN=$(MAX_POPULATION)
PI=3.14159265358979F


FLAGS += -DMAX_POPULATION=$(MAX_POPULATION) \
		 -DMAX_GEN=$(MAX_GEN) \
		 -DPI=$(PI) \
		 -DDEFAULT_POPULATION_SIZE=$(DEFAULT_POPULATION_SIZE) \
		 -DDEFAULT_GENES_PER_INDIVIDUAL=$(DEFAULT_GENES_PER_INDIVIDUAL) \
		 -DDEFAULT_LOWER_GENE_LIMIT=$(DEFAULT_LOWER_GENE_LIMIT) \
		 -DDEFAULT_UPPER_GENE_LIMIT=$(DEFAULT_UPPER_GENE_LIMIT) \
		 -DDEFAULT_MUTATION_CHANCE_PERCENT=$(DEFAULT_MUTATION_CHANCE_PERCENT) \
		 -DDEFAULT_CROSSOVER_CHANCE_PERCENT=$(DEFAULT_CROSSOVER_CHANCE_PERCENT) \
		 -DDEFAULT_MAX_GENERATIONS=$(DEFAULT_MAX_GENERATIONS)

$(BUILD)/debug: $(SOURCE)
	$(CC) -I$(INCLUDE) $(FLAGS) -o $@ $^ $(LIBS)

all: build/debug

run:
	./build/debug